import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  lpSidebar: [
    "lp/intro",
    "lp/environment",
    {
      type: "category",
      label: "課題",
      link: {
        type: "generated-index",
        title: "課題",
        slug: "lp/challenge",
        description:
          "旅行シェアサービス「TripShare」のLPページを実装してみましょう！",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "lp/challenge",
        },
      ],
    },
  ],
  crudSidebar: [
    "crud/intro",
    "crud/environment",
    {
      type: "category",
      label: "Laravelの基本",
      link: {
        type: "generated-index",
        title: "Laravelの基本",
        slug: "laravel-basic",
        description: "Laravelの基本について解説します。",
      },
      items: ["crud/laravel/create_controller"],
    },
    {
      type: "category",
      label: "課題",
      link: {
        type: "generated-index",
        title: "課題",
        slug: "crud/challenge",
        description: "映画鑑賞記録アプリ「CinemaLog」を実装してみましょう！",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "crud/challenge",
        },
      ],
    },
  ],

  ecSidebar: ["ec/intro", "ec/environment"],
};

export default sidebars;
