import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  lpSidebar: [
    "lp/intro",
    "lp/environment",
    "lp/start-project",
    {
      type: "category",
      label: "レイアウトの基本",
      link: {
        type: "generated-index",
        title: "レイアウトの基本",
        slug: "html-layout",
        description:
          "HTML/CSSで押さえておきたい基本的なレイアウト手法を学びましょう！",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "lp/html-layout",
        },
      ],
    },
    {
      type: "category",
      label: "課題",
      link: {
        type: "generated-index",
        title: "課題",
        slug: "lp/challenge",
        description:
          "旅行シェアサービス「TripShare」のLPページを実装してみましょう！",
      },
      items: [
        "lp/challenge/intro",
        "lp/challenge/header",
        "lp/challenge/hero",
        "lp/challenge/service",
        "lp/challenge/feature",
        "lp/challenge/voice",
        "lp/challenge/cta",
        "lp/challenge/contact",
        "lp/challenge/footer",
      ],
    },
  ],
  crudSidebar: [
    "crud/intro",
    "crud/environment",
    "crud/start-project",
    {
      type: "category",
      label: "Laravelチュートリアル",
      link: {
        type: "generated-index",
        title: "Laravelチュートリアル",
        slug: "laravel-tutorial",
        description: "Laravelの基本的な使い方をチュートリアルで学びましょう！",
      },
      items: [
        "crud/tutorial/about-laravel",
        "crud/tutorial/about",
        "crud/tutorial/basics",
        "crud/tutorial/migration",
        "crud/tutorial/list",
        "crud/tutorial/create",
        "crud/tutorial/update",
        "crud/tutorial/delete",
        "crud/tutorial/auth",
      ],
    },
    {
      type: "category",
      label: "課題",
      link: {
        type: "generated-index",
        title: "課題",
        slug: "crud/challenge",
        description: "映画鑑賞記録アプリ「CinemaLog」を実装してみましょう！",
      },
      items: [
        "crud/challenge/intro",
        "crud/challenge/db-design",
        "crud/challenge/migration",
        "crud/challenge/url-design",
        "crud/challenge/preparation",
        "crud/challenge/component",
        "crud/challenge/list",
        "crud/challenge/detail",
        "crud/challenge/create",
        "crud/challenge/edit",
        "crud/challenge/top",
      ],
    },
  ],

  ecSidebar: [
    "ec/intro",
    "ec/environment",

    {
      type: "category",
      label: "Next.jsチュートリアル",
      link: {
        type: "generated-index",
        title: "Next.jsチュートリアル",
        slug: "nextjs-basic",
        description:
          "Reactの入門から初めて、Next.jsの基本的な使い方をチュートリアルで学びましょう！",
      },
      items: [
        "ec/tutorial/about",
        "ec/tutorial/start-react",
        "ec/tutorial/component-and-props",
        "ec/tutorial/state-management",
        "ec/tutorial/about-nextjs",
        "ec/tutorial/stylying",
        "ec/tutorial/asset-and-seo",
        "ec/tutorial/routing-and-navigation",
        "ec/tutorial/server-and-cliend-components",
        "ec/tutorial/dynamic-routing-and-route-groups",
        "ec/tutorial/data-fetching",
        "ec/tutorial/segment-rule-files",
        "ec/tutorial/suspense",
      ],
    },
    "ec/start-project",
    "ec/laravel-clean-architecture",
    {
      type: "category",
      label: "課題",
      link: {
        type: "generated-index",
        title: "課題",
        slug: "ec/challenge",
        description: "絵画専門のECサイト「イロアート」を実装してみましょう！",
      },
      items: [
        "ec/challenge/intro",
        "ec/challenge/db-design",
        "ec/challenge/api-design",
        "ec/challenge/migration",
        "ec/challenge/api-implementation",
        "ec/challenge/component",
      ],
    },
  ],
};

export default sidebars;
